### ISSUE TITLE
About the used frames in calculating correlation matrix?

### ISSUE THREAD

**Issue by changxuding** [AkojimaSLP/Beamforming-for-speech-enhancement#2]
Thasnks for sharing your nice code, and I have a question about the number of frames in calculating correlation_matrix of MVDR, why not using all frames but just first 10 and last 10 frames of the audio sample?

**Comment by wrz1999** [comment]
I also want to know, Can you tell me?

**Comment by changxuding** [comment]
> I also want to know, Can you tell me?

assume that the beginning and end of speech are noise
